export const NFT_ABI = [
  "function name() external view returns (string)",
  "function symbol() external view returns (string)",
  "function mintPrice() external view returns (uint256)",
  "function owner() external view returns (address)",
  "function mint() external payable",
  "function burn(uint256 tokenId) external",
  "function setMintPrice(uint256 newPrice) external",
  "function setBaseURI(string calldata newBaseURI) external",
  "function ownerOf(uint256 tokenId) external view returns (address)",
  "function balanceOf(address owner) external view returns (uint256)",
  "function approve(address to, uint256 tokenId) external",
  "function getApproved(uint256 tokenId) external view returns (address)",
  "function isApprovedForAll(address owner, address operator) external view returns (bool)",
  "function setApprovalForAll(address operator, bool _approved) external",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)"
];

export const DEX_ABI = [
  "function name() external view returns (string)",
  "function symbol() external view returns (string)",
  "function decimals() external view returns (uint8)",
  "function totalSupply() external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function transfer(address to, uint256 value) external returns (bool)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function approve(address spender, uint256 value) external returns (bool)",
  "function transferFrom(address from, address to, uint256 value) external returns (bool)",
  "function dexSwapRate() external view returns (uint256)",
  "function DEXtoETH(uint256 dexAmount) external view returns (uint256)",
  "function ETHtoDEX(uint256 ethAmount) external view returns (uint256)",
  "function getDexBalance() external view returns (uint256)",
  "function setDexSwapRate(uint256 swapRate) external",
  "function owner() external view returns (address)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)"
];

export const MARKETPLACE_ABI = [
  "function nftContract() external view returns (address)",
  "function dexContract() external view returns (address)",
  "function buyDex() external payable",
  "function sellDex(uint256 dexAmount) external",
  "function sellNFT(uint256 tokenId, uint256 price) external",
  "function sellNFTForDEX(uint256 tokenId, uint256 dexPrice) external",
  "function buyNFT(uint256 tokenId) external payable",
  "function buyNFTWithDEX(uint256 tokenId, uint256 dexAmount) external",
  "function auction(uint256 tokenId, uint256 minimumPrice, uint256 duration) external",
  "function bid(uint256 tokenId) external payable",
  "function endAuction(uint256 tokenId) external",
  "function sales(uint256 tokenId) external view returns (address seller, uint256 price, bool active, bool isDex)",
  "function auctions(uint256 tokenId) external view returns (address seller, uint256 minimumPrice, uint256 highestBid, address highestBidder, uint256 endTime, bool active)",
  "event ItemListed(address indexed seller, uint256 indexed tokenId, uint256 price)",
  "event ItemSold(address indexed buyer, uint256 indexed tokenId, uint256 price)",
  "event AuctionCreated(address indexed seller, uint256 indexed tokenId, uint256 minimumPrice, uint256 duration)",
  "event AuctionBid(address indexed bidder, uint256 indexed tokenId, uint256 price)",
  "event AuctionEnded(address indexed seller, address indexed buyer, uint256 indexed tokenId, uint256 finalPrice)"
];

export const BANK_ABI = [
  "function setDexToken(address token) external",
  "function setAuthorizedModule(address module, bool enabled) external",
  "function authorizedModules(address module) external view returns (bool)",
  "function getBalance() external view returns (uint256)",
  "function getTokenBalance() external view returns (uint256)",
  "function dexToken() external view returns (address)",
  "function deposit() external payable",
  "function depositToken(uint256 amount) external",
  "function withdraw(address payable recipient, uint256 amount) external",
  "function withdrawToken(address recipient, uint256 amount) external",
  "function owner() external view returns (address)",
  "event Deposited(address indexed sender, uint256 amount)",
  "event Withdrawn(address indexed module, address indexed recipient, uint256 amount)",
  "event TokenDeposited(address indexed sender, uint256 amount)",
  "event TokenWithdrawn(address indexed module, address indexed recipient, uint256 amount)",
  "event AuthorizedModuleUpdated(address indexed module, bool enabled)"
];

export const LOAN_MANAGER_ABI = [
  "function dex() external view returns (address)",
  "function nft() external view returns (address)",
  "function loanCounter() external view returns (uint256)",
  "function paymentCycle() external view returns (uint256)",
  "function interest() external view returns (uint256)",
  "function termination() external view returns (uint256)",
  "function maxLoanDuration() external view returns (uint256)",
  "function DEXloans(uint256 loanId) external view returns (address borrower, uint256 collateral, uint256 amount, uint256 deadline, uint256 paymentsMade, uint256 startTime)",
  "function NFTloans(uint256 tokenId) external view returns (address borrower, address provider, uint256 collateral, uint256 amount, uint256 deadline, uint256 paymentsMade, uint256 startTime)",
  "function loanDEX(uint256 dexAmount, uint256 deadline) external",
  "function makeDEXLoanPayment(uint256 loanId) external payable",
  "function terminateDEXLoan(uint256 loanId) external payable",
  "function checkDEXLoan(uint256 loanId) external",
  "function requestLoanNFT(uint256 loanValue, uint256 tokenId, uint256 deadline) external",
  "function loanNFT(uint256 tokenId) external",
  "function makeNFTLoanPayment(uint256 tokenId) external payable",
  "function terminateNFTLoan(uint256 tokenId) external payable",
  "function checkNFTLoan(uint256 tokenId) external",
  "function setPaymentCycle(uint256 value) external",
  "function setInterest(uint256 value) external",
  "function setTerminationFee(uint256 value) external",
  "function setMaxLoanDuration(uint256 value) external",
  "function owner() external view returns (address)",
  "event DEXloanCreated(address indexed borrower, uint256 amount, uint256 deadline)",
  "event DEXloanFinished(address indexed borrower, uint256 amount)",
  "event NFTloanRequested(address indexed borrower, uint256 amount, uint256 deadline)",
  "event NFTloanCreated(address indexed borrower, address indexed provider, uint256 amount, uint256 deadline)",
  "event NFTloanFinished(address indexed borrower, address indexed provider, uint256 amount)"
];
